# Generated by Django 3.2.9 on 2021-11-30 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.PositiveIntegerField()),
                ('studentClass', models.CharField(choices=[('M', 'Math'), ('C', 'Chemistry'), ('P', 'Picture')], max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.student')),
            ],
        ),
    ]
