# Generated by Django 3.2.9 on 2021-11-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0002_auto_20211129_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='principal',
            field=models.ManyToManyField(through='LoginPage.Student', to='LoginPage.Principal'),
        ),
    ]
