# Generated by Django 4.0 on 2021-12-09 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teknisyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aktif', models.BooleanField(default=1)),
                ('AdSoyad', models.CharField(max_length=255, verbose_name='Adı Soyadı')),
                ('KayitTarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Teknisten',
                'verbose_name_plural': 'Teknisyenler',
            },
        ),
    ]
