# Generated by Django 4.0 on 2021-12-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teknikservis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teknisyen',
            options={'verbose_name': 'Teknisyen', 'verbose_name_plural': 'Teknisyenler'},
        ),
    ]
